version: '3.5'
services:
  backend:
    image: ${registry}:latest
    ports:
      - '5000:5000'
    environment:
      - CONNECTION_URL=${CONNECTION_URL}
      - registry=${registry}
      - PORT=${PORT}