version: '3.5'
services:
  bloback:
    image: rithvikramasani/bloback:latest
    ports:
      - "3001:3002"
    environment:
      - PORT=3001
      - CONNECTION_URL=mongodb+srv://rithvikramasani:rithvikramasani@cluster0.sgvjxgt.mongodb.net/
  